version: '3.7'

services:
  tree_menu_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  tree_menu-db:
    image: postgres:12.0-alpine
    volumes:
      - tree_menu_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  tree_menu_postgres_data: